server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/html;
    
    client_max_body_size 20M;
    client_body_buffer_size 128k;

    location ^~ /phpmyadmin/ {
        proxy_pass http://ipm-pma:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri $uri/ @php_rewrite;
    }

    location @php_rewrite {
        # Check if the .php file exists, if so rewrite to it, else fallback to index.php
        if (-f $document_root$uri.php) {
            rewrite ^(.*)$ $1.php last;
        }
        rewrite ^ /index.php?$query_string last;
    }
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
